---
namespace: https://github.com/cri-o/crio-credential-provider
license: Apache-2.0
name: crio-credential-provider
creator:
  person: The CRI-O Authors
  tool: crio-credential-provider

artifacts:
  - type: file
    source: crio-credential-provider-linux-amd64
    license: Apache-2.0
    gomodules: true

  - type: file
    source: crio-credential-provider-linux-arm64
    license: Apache-2.0
    gomodules: true

  - type: file
    source: crio-credential-provider-linux-ppc64le
    license: Apache-2.0
    gomodules: true

  - type: file
    source: crio-credential-provider-linux-s390x
    license: Apache-2.0
    gomodules: true
