---
codecov:
  notify:
    after_n_builds: 1
  require_ci_to_pass: false

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

comment:
  layout: "header, diff"
  behavior: default
  require_changes: false
